In [1]:
import warnings

warnings.filterwarnings("ignore")

In [27]:
import seaborn
import pandas as pd
import geopandas
import pysal
import numpy
import matplotlib.pyplot as plt

In [91]:
avg_n = geopandas.read_file("alt_data/cleaned_avg_temp_by_ng_states.shp")
#mx[["NAME", "PCGDP1940"]].head()
mx.head()

,globalid,uniq_id,statename,geozone,1990,1991,1992,1993,1994,1995,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,geometry
0,c46ae452-d6b6-4618-b3f7-ed6015e978d7,1187,Cross River,SSZ,25.87,25.64,25.65,25.88,25.90,26.00,...,26.33,26.50,26.75,26.78,26.57,26.61,26.96,26.91,26.67,"POLYGON ((8.46076 4.75455, 8.45885 4.75393, 8...."
1,0e73256c-2793-44cc-ab1b-7289f145b866,1175,Abuja FCT,NCZ,27.36,27.08,26.67,27.15,27.04,27.14,...,27.44,27.61,27.68,28.17,27.50,27.64,27.71,28.08,27.63,"POLYGON ((7.47762 8.63133, 7.44303 8.59328, 7...."
2,7f0787e4-4518-4486-8bc5-51c5232df9d1,1190,Ogun,SWZ,26.26,26.05,26.01,26.22,26.17,26.37,...,26.62,26.77,27.21,27.01,26.87,27.11,27.20,27.36,26.98,"POLYGON ((4.59755 6.36057, 4.59757 6.35688, 4...."
3,0edbae77-0091-40d9-afdf-7e249ed797fb,1191,Oyo,SWZ,26.27,25.98,25.86,26.12,26.10,26.28,...,26.59,26.77,27.08,27.00,26.66,26.86,26.96,27.36,26.85,"POLYGON ((3.99896 7.12657, 3.99755 7.12617, 3...."
4,143c5cd1-9f44-4935-ab8a-891e4c05451e,1177,Sokoto,NWZ,28.86,28.37,27.86,28.71,28.04,28.55,...,29.07,28.95,29.21,29.04,28.87,29.02,28.97,29.38,28.58,"POLYGON ((4.63265 11.67143, 4.62886 11.66810, ..."

In [92]:
avg_n[["statename", "1990"]].head()

     statename   1990
0  Cross River  25.87
1    Abuja FCT  27.36
2         Ogun  26.26
3          Oyo  26.27
4       Sokoto  28.86